HEX
FE000000 CONSTANT RPI4

: BIT_SET 1 SWAP LSHIFT OR ;
: BIT_CLEAR 1 SWAP LSHIFT INVERT AND ;

: 3BIT_SET 7 SWAP LSHIFT OR ;
: 3BIT_CLEAR 7 SWAP LSHIFT INVERT AND ;

: 4BIT_SET F SWAP LSHIFT OR ;
: 4BIT_CLEAR F SWAP LSHIFT INVERT AND ;

: 16BIT_SET FFFF SWAP LSHIFT OR ;
: 16BIT_CLEAR FFFF SWAP LSHIFT INVERT AND ;

: DELAY BEGIN 1 - DUP 0 = UNTIL DROP ;

