HEX
FE000000 CONSTANT RPI4

: BIT_SET 1 SWAP LSHIFT OR ;
: BIT_CLEAR 1 SWAP LSHIFT INVERT AND ;

: 3BIT_SET 7 SWAP LSHIFT OR ;
: 3BIT_CLEAR 7 SWAP LSHIFT INVERT AND ;

: 4BIT_SET F SWAP LSHIFT OR ;
: 4BIT_CLEAR F SWAP LSHIFT INVERT AND ;

: 16BIT_SET FFFF SWAP LSHIFT OR ;
: 16BIT_CLEAR FFFF SWAP LSHIFT INVERT AND ;

: STACK_CLEAR BEGIN DEPTH 0 > WHILE DROP REPEAT ;

( LED - BUTTON )
: RED 6 C ;
: BLUE D 10 ;
: GREEN 13 14 ;
: YELLOW 1A 15 ;
: RESET 0 A ;
: POWER 0 5 ;

( BUZZER )
: BUZZER 12 ;

( 7-SEGMENT DISPLAY )
: A_SEGMENT 17 ;
: B_SEGMENT 18 ;
: C_SEGMENT 16 ;
: D_SEGMENT 1B ;
: E_SEGMENT 11 ;
: F_SEGMENT 19 ;
: G_SEGMENT 4 ;

( I2C BUS )
: SDA 2 ;
: SCL 3 ;

