RPI4 200000 + CONSTANT GPIO

GPIO 00 + CONSTANT GPFSEL0
GPIO 04 + CONSTANT GPFSEL1
GPIO 08 + CONSTANT GPFSEL2
GPIO 0C + CONSTANT GPFSEL3
GPIO 10 + CONSTANT GPFSEL4
GPIO 14 + CONSTANT GPFSEL5

GPIO 1C + CONSTANT GPSET0
GPIO 20 + CONSTANT GPSET1

GPIO 28 + CONSTANT GPCLR0
GPIO 2C + CONSTANT GPCLR1

GPIO 34 + CONSTANT GPLEV0
GPIO 38 + CONSTANT GPLEV1

GPIO 34 + CONSTANT GPLEV0
GPIO 38 + CONSTANT GPLEV1

: ?GPFSEL 
	DUP 9 <= IF GPFSEL0 ELSE 
	DUP 13 <= IF GPFSEL1 ELSE 
	DUP 1D <= IF GPFSEL2 ELSE
	DUP 27 <= IF GPFSEL2 ELSE
	DUP 31 <= IF GPFSEL2 ELSE
	DUP 39 <= IF GPFSEL2 ELSE
	." ERROR: GPIO NUMBER NOT VALID!"
	THEN THEN THEN THEN THEN THEN NIP ;


: BIC A MOD 3 * DUP 7 SWAP LSHIFT INVERT ROT AND ;

: GPIO_MODE  DUP ?GPFSEL DUP @ ROT BIC ;

: INPUT		SWAP 0 SWAP LSHIFT OR SWAP ! ;
: OUTPUT 	SWAP 1 SWAP LSHIFT OR SWAP ! ;
: ALT_0 	SWAP 4 SWAP LSHIFT OR SWAP ! ;
: ALT_1 	SWAP 5 SWAP LSHIFT OR SWAP ! ;
: ALT_2 	SWAP 6 SWAP LSHIFT OR SWAP ! ;
: ALT_3 	SWAP 7 SWAP LSHIFT OR SWAP ! ;
: ALT_4 	SWAP 3 SWAP LSHIFT OR SWAP ! ;
: ALT_5 	SWAP 2 SWAP LSHIFT OR SWAP ! ;

: ?GPSETCLR
	DUP 1F <= IF DROP GPSET0 GPCLR0 ELSE 
	DUP 39 <= IF DROP GPSET1 GPCLR1 ELSE 
	." ERROR: GPIO NUMBER NOT VALID!"
	THEN THEN ;

: GPIO_OUTPUT DUP 20 MOD 1 SWAP LSHIFT SWAP ?GPSETCLR ;
: ON DROP ! ;
: OFF NIP ! ;