HEX
FE000000 CONSTANT RPI4

: BIT_SET 1 SWAP LSHIFT OR ;
: BIT_CLEAR 1 SWAP LSHIFT INVERT AND ;

: 3BIT_SET 7 SWAP LSHIFT OR ;
: 3BIT_CLEAR 7 SWAP LSHIFT INVERT AND ;

: DELAY BEGIN 1 - DUP 0 = UNTIL DROP ;